// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenchain/core/v1/block_record.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BlockRecord defines the BlockRecord message.
type BlockRecord struct {
	Index    string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Height   string `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	Hash     string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Proposer string `protobuf:"bytes,4,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Time     string `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Creator  string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *BlockRecord) Reset()         { *m = BlockRecord{} }
func (m *BlockRecord) String() string { return proto.CompactTextString(m) }
func (*BlockRecord) ProtoMessage()    {}
func (*BlockRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7a7bec93236b35c, []int{0}
}
func (m *BlockRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRecord.Merge(m, src)
}
func (m *BlockRecord) XXX_Size() int {
	return m.Size()
}
func (m *BlockRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRecord proto.InternalMessageInfo

func (m *BlockRecord) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *BlockRecord) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *BlockRecord) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockRecord) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *BlockRecord) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *BlockRecord) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockRecord)(nil), "tokenchain.core.v1.BlockRecord")
}

func init() {
	proto.RegisterFile("tokenchain/core/v1/block_record.proto", fileDescriptor_c7a7bec93236b35c)
}

var fileDescriptor_c7a7bec93236b35c = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbd, 0x4a, 0xc4, 0x40,
	0x14, 0x46, 0x33, 0xba, 0x1b, 0x75, 0xec, 0x2e, 0xa2, 0x83, 0xc5, 0x20, 0x82, 0x60, 0x95, 0x10,
	0x7c, 0x83, 0x7d, 0x84, 0x2d, 0x6d, 0x24, 0x3b, 0x7b, 0x71, 0x86, 0x68, 0xee, 0x70, 0x33, 0x84,
	0xf8, 0x16, 0xb6, 0xbe, 0x91, 0x65, 0x4a, 0x4b, 0x49, 0x5e, 0x44, 0x66, 0xe2, 0x5f, 0xf7, 0x9d,
	0xc3, 0x69, 0x3e, 0x79, 0x13, 0xa8, 0xc1, 0xd6, 0xd8, 0xda, 0xb5, 0xa5, 0x21, 0xc6, 0xb2, 0xaf,
	0xca, 0xdd, 0x13, 0x99, 0xe6, 0x81, 0xd1, 0x10, 0xef, 0x0b, 0xcf, 0x14, 0x08, 0xe0, 0x2f, 0x2b,
	0x62, 0x56, 0xf4, 0xd5, 0xf5, 0x9b, 0x90, 0xa7, 0x9b, 0x98, 0x6e, 0x53, 0x09, 0x67, 0x72, 0xed,
	0xda, 0x3d, 0x0e, 0x4a, 0x5c, 0x89, 0xdb, 0x93, 0xed, 0x02, 0x70, 0x2e, 0x73, 0x8b, 0xee, 0xd1,
	0x06, 0x75, 0x90, 0xf4, 0x37, 0x01, 0xc8, 0x95, 0xad, 0x3b, 0xab, 0x0e, 0x93, 0x4d, 0x1b, 0x2e,
	0xe5, 0xb1, 0x67, 0xf2, 0xd4, 0x21, 0xab, 0x55, 0xf2, 0xbf, 0x1c, 0xfb, 0xe0, 0x9e, 0x51, 0xad,
	0x97, 0x3e, 0x6e, 0x50, 0xf2, 0xc8, 0x30, 0xd6, 0x81, 0x58, 0xe5, 0x49, 0xff, 0xe0, 0xa6, 0x7a,
	0x9f, 0xb4, 0x18, 0x27, 0x2d, 0x3e, 0x27, 0x2d, 0x5e, 0x67, 0x9d, 0x8d, 0xb3, 0xce, 0x3e, 0x66,
	0x9d, 0xdd, 0x5f, 0xfc, 0x3b, 0x3c, 0x2c, 0x97, 0xc3, 0x8b, 0xc7, 0x6e, 0x97, 0xa7, 0xa7, 0x77,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x5f, 0xee, 0x0d, 0x12, 0x01, 0x00, 0x00,
}

func (m *BlockRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBlockRecord(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Time) > 0 {
		i -= len(m.Time)
		copy(dAtA[i:], m.Time)
		i = encodeVarintBlockRecord(dAtA, i, uint64(len(m.Time)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintBlockRecord(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintBlockRecord(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintBlockRecord(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintBlockRecord(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBlockRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovBlockRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BlockRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovBlockRecord(uint64(l))
	}
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovBlockRecord(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovBlockRecord(uint64(l))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovBlockRecord(uint64(l))
	}
	l = len(m.Time)
	if l > 0 {
		n += 1 + l + sovBlockRecord(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBlockRecord(uint64(l))
	}
	return n
}

func sovBlockRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBlockRecord(x uint64) (n int) {
	return sovBlockRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BlockRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlockRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Time = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBlockRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBlockRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBlockRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBlockRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBlockRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBlockRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBlockRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBlockRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBlockRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBlockRecord = fmt.Errorf("proto: unexpected end of group")
)
