// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmoschain/core/v1/miner.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Miner defines the Miner message.
type Miner struct {
	Index       string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Power       string `protobuf:"bytes,3,opt,name=power,proto3" json:"power,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TotalReward string `protobuf:"bytes,5,opt,name=total_reward,json=totalReward,proto3" json:"total_reward,omitempty"`
	Creator     string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Miner) Reset()         { *m = Miner{} }
func (m *Miner) String() string { return proto.CompactTextString(m) }
func (*Miner) ProtoMessage()    {}
func (*Miner) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a80067874d3f3f0, []int{0}
}
func (m *Miner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Miner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Miner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Miner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Miner.Merge(m, src)
}
func (m *Miner) XXX_Size() int {
	return m.Size()
}
func (m *Miner) XXX_DiscardUnknown() {
	xxx_messageInfo_Miner.DiscardUnknown(m)
}

var xxx_messageInfo_Miner proto.InternalMessageInfo

func (m *Miner) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Miner) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Miner) GetPower() string {
	if m != nil {
		return m.Power
	}
	return ""
}

func (m *Miner) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Miner) GetTotalReward() string {
	if m != nil {
		return m.TotalReward
	}
	return ""
}

func (m *Miner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Miner)(nil), "cosmoschain.core.v1.Miner")
}

func init() { proto.RegisterFile("cosmoschain/core/v1/miner.proto", fileDescriptor_1a80067874d3f3f0) }

var fileDescriptor_1a80067874d3f3f0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4e, 0x03, 0x31,
	0x10, 0x45, 0xd7, 0xc0, 0x06, 0x61, 0xa8, 0x0c, 0x85, 0x69, 0x4c, 0xa0, 0xa2, 0x61, 0x57, 0x51,
	0x6e, 0x40, 0x4f, 0x93, 0x92, 0x06, 0x19, 0x7b, 0x24, 0x2c, 0x11, 0x8f, 0x35, 0xb6, 0x92, 0x70,
	0x0b, 0x0e, 0xc2, 0x41, 0x28, 0x53, 0x52, 0xa2, 0xdd, 0x8b, 0x20, 0xdb, 0x44, 0xda, 0xf2, 0x3d,
	0x3f, 0x69, 0xf4, 0xcd, 0x6f, 0x0c, 0xc6, 0x35, 0x46, 0xf3, 0xa6, 0x9d, 0xef, 0x0d, 0x12, 0xf4,
	0x9b, 0x45, 0xbf, 0x76, 0x1e, 0xa8, 0x0b, 0x84, 0x09, 0xc5, 0xe5, 0x24, 0xe8, 0x72, 0xd0, 0x6d,
	0x16, 0x77, 0x5f, 0x8c, 0xb7, 0x4f, 0x39, 0x12, 0x57, 0xbc, 0x75, 0xde, 0xc2, 0x4e, 0xb2, 0x39,
	0xbb, 0x3f, 0x5b, 0x55, 0x10, 0x92, 0x9f, 0x6a, 0x6b, 0x09, 0x62, 0x94, 0x47, 0xc5, 0x1f, 0x30,
	0xf7, 0x01, 0xb7, 0x40, 0xf2, 0xb8, 0xf6, 0x05, 0xc4, 0x9c, 0x9f, 0x5b, 0x88, 0x86, 0x5c, 0x48,
	0x0e, 0xbd, 0x3c, 0x29, 0x6f, 0x53, 0x25, 0x6e, 0xf9, 0x45, 0xc2, 0xa4, 0xdf, 0x5f, 0x08, 0xb6,
	0x9a, 0xac, 0x6c, 0x6b, 0x52, 0xdc, 0xaa, 0xa8, 0x7c, 0xd4, 0x10, 0xe8, 0x84, 0x24, 0x67, 0xf5,
	0xe8, 0x3f, 0x3e, 0x2e, 0xbf, 0x07, 0xc5, 0xf6, 0x83, 0x62, 0xbf, 0x83, 0x62, 0x9f, 0xa3, 0x6a,
	0xf6, 0xa3, 0x6a, 0x7e, 0x46, 0xd5, 0x3c, 0x5f, 0xd7, 0x75, 0x0f, 0x75, 0xff, 0xae, 0xfe, 0x40,
	0xfa, 0x08, 0x10, 0x5f, 0x67, 0x65, 0xff, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x18, 0xd4, 0x31,
	0x55, 0x22, 0x01, 0x00, 0x00,
}

func (m *Miner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Miner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Miner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TotalReward) > 0 {
		i -= len(m.TotalReward)
		copy(dAtA[i:], m.TotalReward)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.TotalReward)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Power) > 0 {
		i -= len(m.Power)
		copy(dAtA[i:], m.Power)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Power)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMiner(dAtA []byte, offset int, v uint64) int {
	offset -= sovMiner(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Miner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.Power)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.TotalReward)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	return n
}

func sovMiner(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMiner(x uint64) (n int) {
	return sovMiner(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Miner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMiner
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Miner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Miner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Power = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalReward = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMiner(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMiner
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMiner(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMiner
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMiner
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMiner
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMiner
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMiner        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMiner          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMiner = fmt.Errorf("proto: unexpected end of group")
)
